inherit_gem:
  relaxed-rubocop: .rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/spring
    - config/deploy.rb
    - vendor/**/*
    - bin/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - "**/config/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/app/admin/**/*.rb"
    - "**/app/views/**/*.json.jbuilder"

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading

Rails/FilePath:
  EnforcedStyle: arguments

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Naming/VariableNumber:
  Enabled: false